### ISSUE TITLE
Please give credit when adapting prior work

### ISSUE THREAD

**Issue by cthoyt** [pschwllr/minimal_project#1]
It would be great if you would give some credit to my cookiecutter template (https://github.com/cthoyt/cookiecutter-snekpack), especially since you copied some things from it verbatim, e.g. https://github.com/pschwllr/minimal_project/blob/237186fc88ce9f21b971f0e2f8c9d17e27c9df9b/README.md?plain=1#L16-L17

The best way to do this is to have a notice at the bottom of the README that says that your project was adapted from mine, and link back to it

**Comment by pschwllr** [comment]
Done :)
